### ISSUE TITLE
Component list is always empty

### ISSUE THREAD

**Issue by JoeyStrandnes** [Funkenjaeger/brd2json#10]
Not sure if this warrants an issue or not but the list of components is always empty regardless of what pass to “InteractiveHtmlBom”. I’m not sure if I’m doing something wrong. 
The board show up correctly and I am able to use the “drawing view” mostly without fault. I am however not able to select the components.  
I’ve tried this with three different PCBs and all are flawed in the same way. 
Im using Eagle v9.6.2 in board view to export the json file and the latest version of InteractiveHtmlBom.

<img src="https://i.imgur.com/dHCL5dt.png" alt="Example" style="zoom:33%;" />

**Comment by Funkenjaeger** [comment]
Thanks for reporting, I'll take a look.  

Just to be sure, you are using the version of the script from the [eagle branch](https://github.com/Funkenjaeger/brd2json/tree/eagle) right?

I just used the script successfully with the latest InteractiveHtmlBom a week or so ago, but that was with Fusion 360 Electronics -and admittedly I didn't go back and regression test with Eagle at that time, so I may have missed a compatibility issue if there is one.

**Comment by JoeyStrandnes** [comment]
No problem.

Yes, I was using the eagle branch. I tried it with both versions, the ULP script couldn't complete if the wrong version was chosen.

**Comment by Funkenjaeger** [comment]
Hmm, I just tested a board of mine with Eagle 9.6.2 and the latest InteractiveHtmlBom (commit 4b2394ac4f117904986ba5eebfd678cde30a2c32) and didn't see any issues (screenshot below).  Can you share an example .BRD file that's exhibiting this problem for you?
![image](https://user-images.githubusercontent.com/24237058/128096582-a165ef35-717a-4e9a-8547-62d4d8333f45.png)

**Comment by Funkenjaeger** [comment]
Or conversely, does the JSON file I just generated work properly for you with InteractiveHtmlBom?  (attached, zipped)
[ESS switch breakout.zip](https://github.com/Funkenjaeger/brd2json/files/6927488/ESS.switch.breakout.zip)

**Comment by JoeyStrandnes** [comment]
Hi, 

I tried your JSON file and got the same result.
I guess that it has something to do with interactive BOM so you’re off the hook :P
Strange that it works fine with KiCAD...

Thanks for looking into it.

**Comment by Funkenjaeger** [comment]
One last shot in the dark: the HTML ibom does have some options in the header for which side of the board is displayed, which will affect the components in the list.  Does that make any difference for you?  If you view the board stats, does it actually say there are zero components?
![image](https://user-images.githubusercontent.com/24237058/128223983-0deb578a-a334-4756-b809-2fa0c9073bfd.png)

Can you share your generated ibom HTML file?  The pcb data (including list of components) is embedded within that HTML file as a Base64 blob; given the file it may be possible to find a clue about what's going wrong by decompressing that and looking at the JSON object.

**Comment by JoeyStrandnes** [comment]
Hi, 

It doesn't actually say that I have zero components something i found strange when first trying it out. 

Thanks again for looking into this!

I've attached the requested files.

<img src="https://i.imgur.com/XPVr0pc.png" style="zoom:50%;" />

[ESS-GitHub.zip](https://github.com/Funkenjaeger/brd2json/files/6959440/ESS-GitHub.zip)

**Comment by Funkenjaeger** [comment]
I extracted the 'pcbdata' blob from the HTML file you shared, and did the same for my own file.

There is exactly one difference - the ibom version string:
![image](https://user-images.githubusercontent.com/24237058/128855996-6f37aec4-ddbc-4b3f-bdda-8760ef387e47.png)
That's just metadata, all the data regarding the board and bom is the same, so at first glance it doesn't seem that that should have made the difference. 

However, if you open your browser console you'll see that there's a javascript error:
```
Uncaught TypeError: Cannot read property '0' of null
    at populateMetadata (ESS-GitHub.html:3735)
    at window.onload (ESS-GitHub.html:4065)
```
The specific line on which that is occurring is:
```
  // Update version string
  document.getElementById("github-link").innerHTML = "InteractiveHtmlBom&nbsp;" +
    /^v\d+\.\d+/.exec(pcbdata.ibom_version)[0];
```

So, it appears that the javascript 'exec' function is choking on your ibom version string.
Poking at it a little more, it seems that your version string doesn't match the regex because it has a leading dot (v.0.5 versus v0.5) - if that dot weren't there the command succeeds:
![image](https://user-images.githubusercontent.com/24237058/128857011-c7fafdc9-1bdb-4a7a-9c3e-e677cf31245d.png)

(I didn't go through the effort of trying to turn the JSON with 'fixed' version string back into a Base64 blob and reinsert it into the HTML file)

**Comment by Funkenjaeger** [comment]
In other words, this seems to be a problem specific to whatever fork of InteractiveHtmlBom you're using.  The version number in my file (on the left in the compare above) is the latest commit from upstream (sha starts with 4b23)
