### ISSUE TITLE
Doesn't work for current Eagle version(s)

### ISSUE THREAD

**Issue by jelli123** [Funkenjaeger/brd2json#19]
There seem to be some incompatible changes in the ULP. Honestly, I don't know since when exactly.
The attached version works with Eagle 9.6.2 
[brd2json.zip](https://github.com/Funkenjaeger/brd2json/files/8612136/brd2json.zip)

**Comment by Funkenjaeger** [comment]
Per the Eagle documentation, from version 9.1.0 onward:
```
V9.1.0 – There is a change in the terminology. From now on all objects know
as Package are named Footprint. For compatibility reasons, package is still
valid, for example in Scripts or ULPs.
The User Language now understands the new aliases UL_FOOTPRINT,
footprint(), .footprints, .footprint.
```

As such, I switched to using 'package' with PR #15 for backward compatibility, because at least one person was still using an ancient version of Eagle.  At the time, I tested it and it seemed to be working with 9.6.2.

You'll have to provide some information about what issue you're actually experiencing in order for me to be able to investigate it - ideally please share an example BRD file that exhibits an issue with the ULP.

**Comment by jelli123** [comment]
In Eagle 9.6.2 the ULP stops immediately with all my board files. "C:/.../brd2json.ulp(98): syntax error".
UL_POLYSHAPE and UL_POLYPOUR are not present in ULP Documentation. I changed it to UL_POLYGON and B.polyShapes/S.polyPours to B.polygons/S.polygons and there is no syntax error anymore.

**Comment by Funkenjaeger** [comment]
Okay, I misunderstood your issue.  Based on what you just clarified, it appears that you're using `main` (which is for Fusion 360 Electronics only) rather than [the `eagle` branch](https://github.com/Funkenjaeger/brd2json/tree/eagle) as indicated in the readme.  The 'footprint' thing I mentioned above is backward-compatible, but unfortunately Autodesk's change from polygon to polyshape/polypour offers no such option for backward compatibility to my knowledge, so I'm forced to carry separate versions of the ULP for Eagle vs. Fusion.

**Comment by jelli123** [comment]
Oh yes, thx for clarification. It was printed to bold recognizing it ;-) I will close this issue.
