### ISSUE TITLE
Syntax error when running in Eagle 9.6.2

### ISSUE THREAD

**Issue by gromain** [Funkenjaeger/brd2json#9]
I have a syntax error on line 94 when running in Eagle 9.6.2 on the board [here](https://github.com/PlanktonPlanet/PlanktonScope/blob/master/hardware/HAT/PlanktoscopeHat-v0.1-fab.brd).

It seems like the error is in this line: `void AddPolyShape(UL_POLYSHAPE P, int L, int indent)`. But nothing jumps up to me as to what might be wrong here...

Anything I can do on my side to help?

**Comment by gromain** [comment]
Maybe it's because I'm not using the `eagle` branch, but I can't find it! Has it been pushed?

**Comment by Funkenjaeger** [comment]
My mistake, I forgot to push the eagle branch - sorry about that!  Should be set now.

**Comment by gromain** [comment]
Ah thanks, I just pulled and updated.
It seems like I now run into #3 ... I have an error with `Invalid layer while accessing 'dx[1]'`. Has #6 been merged into the eagle branch?

**Comment by Funkenjaeger** [comment]
Give it another try.  Since my above comment, I went ahead and rebased the eagle branch onto main and made the necessary changes to make polygons work in Eagle.  So, now the eagle branch is fully caught up with the fixes and features in main (including text, nets, etc). 

Let me know if it works for you (or not!)

**Comment by gromain** [comment]
Same error still, but different line now (317): `Invalid layer while accessing 'dx[1]'`. I have weird cutout on my board, could this be the reason?

The board is available [here](https://github.com/PlanktonPlanet/PlanktonScope/blob/master/hardware/HAT/PlanktoscopeHat-v0.1-fab.brd) if you want to try yourself to help debugging!

If there is anything I can do to help, please let me know!

**Comment by Funkenjaeger** [comment]
This was an interesting one, thanks for sharing the file.  Turns out that there was a latent bug related to #3, and the workaround put in place for that was (not surprisingly) not a real fix.  Your file helped expose the underlying issue, so that is now properly fixed.

Now your board processes without an error, however there are one or more other issues that I'm trying to understand.
- The GND pour render covers the entire board rather than having cutouts - this doesn't happen if I process the same BRD through Fusion instead, so it seems to be something unique to Polygons in Eagle.
- There are a bunch of nets that don't seem to have any corresponding copper

I'll keep you posted if/when I figure out more of this...

**Comment by Funkenjaeger** [comment]
Okay, I've solved the above issues.

- In Eagle, if you haven't ratsnested then the polygon pours (copper) render as whatever outline you drew for the pour, i.e. without conforming to the board outline or clearance for other traces/vias/etc.  So, I added a line to force a ratsnest prior to processing.
- Only nets which have copper (traces and/or vias) get included in the netlist now

There's one more little issue your board has exposed, which is that InteractiveHtmlBom doesn't support curved traces - since KiCad doesn't support them, there isn't a provision in the data structures to accommodate such a thing.  For now I've simply disabled processing curved traces (they just won't show up), but a real fix will require a change to InteractiveHtmlBom.  I'll submit an issue there (and a PR, if I can figure out how to solve it)

**Comment by gromain** [comment]
Hey,

Thanks for all that! All because of me! I'm glad this is working now! Even if the curved traces aren't showing, it's still a great tool!
Let me know if there is anything I can do to help!

**Comment by Funkenjaeger** [comment]
InteractiveHtmlBom issue: https://github.com/openscopeproject/InteractiveHtmlBom/issues/229
On my fork, I've got this working already so it should be just a matter of time (working with the developer) to get this incorporated in ibom main.
Pull request in process: https://github.com/openscopeproject/InteractiveHtmlBom/pull/230
![image](https://user-images.githubusercontent.com/24237058/109403412-7d705300-792b-11eb-97d7-de10c025682b.png)

**Comment by gromain** [comment]
Awesome, thanks for your work!

**Comment by Funkenjaeger** [comment]
The InteractiveHtmlBom changes have been merged, so the curved traces on your board should work now.  I'll leave this issue open until I've had the chance to go back and verify it.

**Comment by gromain** [comment]
Hey, I've just tested and apart from an upstream problem with python3.9 (that I've raised), it looks like everything is working perfectly!
Thanks a lot for this work!
